### ISSUE TITLE
Lua 的使用方式是否错误 ？

### ISSUE THREAD

**Issue by gamenite** [no5ix/realtime-server#3]
我对比了一下 skynet，云风是用 lua 来调用底层 c ，而作者你代码是用 c++ 来调用 lua，或者说是用 lua 来填 c++ 的函数。
本人愚昧，作者能否辨析一下这两种方式。感谢😘

**Comment by no5ix** [comment]
一般不会这么玩，我这样只是弄着玩XD


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
